#include <stdio.h>
#include <stdbool.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_keycode.h>

#define STB_IMAGE_IMPLEMENTATION 1
#include <stb_image.h>

#define STB_RECT_PACK_IMPLEMENTATION 1
#include <stb_rect_pack.h>

#define STB_TRUETYPE_IMPLEMENTATION 1
#include <stb_truetype.h>

#include "core/core.h"
#include "core/types.h"
#include "game/npc.h"
#include "os/core.h"

#include "vulkan/core.h"
#include "draw/core.h"

#include "game/core.h"

#include "game/impl/world.c"
#include "game/impl/npc.c"
#include "game/impl/bandit.c"
#include "game/testnavmesh.h"

int main(int argc, char **argv)
{
	(void)argc;
	(void)argv;

	if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO))
	{
		printf("[Error] :: Failed to initialise SDL3 (%s)\n", SDL_GetError());
		return 1;
	}

	SDL_Window *window = SDL_CreateWindow("Ludum", 1280, 720, SDL_WINDOW_HIGH_PIXEL_DENSITY);
	if (!window)
	{
		printf("[Error] :: Failed to create window (%s)\n", SDL_GetError());
		return 1;
	}

	SDL_AudioStream *austream;
	Str8 audio_data;
	M_TempScope(0, 0) {
		SDL_AudioSpec spec;
		spec.format   = SDL_AUDIO_S16LE;
		spec.channels = 2;
		spec.freq     = 44100;

		austream = SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, &spec, 0, 0);

		if (!austream) {
			printf("Failed to open audio stream (%s)\n", SDL_GetError());
		}

		Str8 exec = FS_SystemPath(temp.arena, FS_SYSTEM_PATH_EXE);
		Str8 path = Sf(temp.arena, "%.*s/assets/outside_ambience.wav", Sv(exec));

		SDL_AudioSpec wav_spec;
		U32 count;

		SDL_LoadWAV((const char *) path.data, &wav_spec, &audio_data.data, &count);
		audio_data.count = count;
	}

	Vk_Setup(window);

	G_State *game = 0;
	{
		M_Arena *arena = M_ArenaAlloc(GB(64), .initial = MB(4));
		game = M_ArenaPush(arena, G_State);

		game->arena      = arena;
		game->draw.arena = arena;

		G_ImagesLoad(game);
		G_PipelinesLoad(game);
		G_AudioLoad(game);

		G_Camera *camera = &game->camera;

		camera->x = V3F(1, 0, 0);
		camera->y = V3F(0, 1, 0);
		camera->z = V3F(0, 0, 1);
		camera->p = V3F(0, 0, 48);

		camera->fov = 60.0f;

		camera->nearp = 0.01f;
		camera->farp = 1000.0f;

		game->draw.camera = camera;
		World *world = M_ArenaPush(arena, World);
    game->world = world;
    world->random = Random_Seed(29237489723847);
    world->npcCount = 1;
    for(U32 i = 0; i < world->npcCount; i++) {
    NPC *npc1 = &world->npcs[i];
      npc1->collision.pos.x = 15;
      npc1->collision.pos.y = 15;
      npc1->collision.size.x = 1;
      npc1->collision.size.y = 1;
      npc1->name = S("Matt");
      npc1->mode = NPC_ACTION_WAITING;
      npc1->waitTime = 0;
      npc1->maxWaitTime = 5;
      npc1->currentNavNode = 0;
      npc1->collision.pos.x = 15;
      npc1->collision.pos.y = 15;
      npc1->collision.size.x = 10;
      npc1->collision.size.y = 10;
    }

    Bandit *badman = &world->bandit;
		badman->collision.pos.x = 15;
		badman->collision.pos.y = 15;
		badman->collision.size.x = 10;
		badman->collision.size.y = 10;
		badman->name = S("Leroy Brown");
		badman->mode = BANDIT_WAITING;
		badman->waitTime = 0;
		badman->maxWaitTime = 2;
		badman->poiCount = 2;
    badman->pointsOfInterest[0] = 937;
    badman->pointsOfInterest[1] = 12;

		world->navMesh = &TestNavMesh;
		world->npcPOI[0] = 100;
		world->player.pos.x = 0;
		world->player.pos.y = 0;
		world->player.bulletsLoaded = PLAYER_BULLET_COUNT;
		world->player.reloadTimer = 0;
	}


	D_Animation animation;
	{
		U32 id = D_ImageHandle(&game->draw, S("npc_front_base_white"));
		D_AnimationInit(&animation, id, 1, 4, 1.0f / 20.0f);
	}

	bool running = true;

	printf("%zu size in bytes\n", sizeof(TestNavMesh));

	while (running)
	{
		SDL_Event e;
		while (SDL_PollEvent(&e))
		{
			if (e.type == SDL_EVENT_QUIT)
			{
				running = false;
			}

      ProcessEvents(&e, game->world);
		}

		UpdateWorld(1.0f / 60.0f, game->world);
		D_AnimationUpdate(&animation, 1.0f / 250.0f);
    game->camera.p.x = game->world->player.pos.x;
    game->camera.p.y = game->world->player.pos.y;

		int w, h;
		SDL_GetWindowSizeInPixels(window, &w, &h);

		game->draw.window_width = w;
		game->draw.window_height = h;

		G_CalculateCamera(&game->camera, (F32)w / (F32)h);

		Vk_Frame *frame = Vk_FrameBegin(window);
		VkCommandBuffer cmd = frame->cmd;

		VkClearValue clear_colour;
		clear_colour.color.float32[0] = 1.0f;
		clear_colour.color.float32[1] = 0.0f;
		clear_colour.color.float32[2] = 0.0f;
		clear_colour.color.float32[3] = 1.0f;

		VkRenderingAttachmentInfo colour_attachment = {0};
		colour_attachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
		colour_attachment.imageView = vk.swapchain.views[frame->image];
		colour_attachment.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
		colour_attachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
		colour_attachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
		colour_attachment.clearValue = clear_colour;

		VkRenderingInfo rendering_info = {0};
		rendering_info.sType = VK_STRUCTURE_TYPE_RENDERING_INFO;
		rendering_info.renderArea = (VkRect2D){0, 0, w, h};
		rendering_info.layerCount = 1;
		rendering_info.colorAttachmentCount = 1;
		rendering_info.pColorAttachments = &colour_attachment;

		vk.CmdBeginRendering(cmd, &rendering_info);

		D_Begin(&game->draw, frame, D_MAX_RECTS);

    //RenderWorld(game->world, &game->draw);
// 		D_Rect(&game->draw, 0.0f, 0.0f, .texture = D_ImageHandle(&game->draw, S("saloon_ext")), .scale = 4.0f);
// 		D_Rect(&game->draw, -8.0f, 0.0f, .texture = 2, .scale = 2.0f);
// 		D_Rect(&game->draw, 6.0f, 0.0f, .texture = 3);

		G_WorldDraw(game, game->world);

		R2f aframe = D_AnimationFrame(&animation);
		D_Rect(&game->draw, 0, 0, .texture = animation.id, .uv = aframe, .flags = D_RECT_UV_ASPECT);

		D_End(&game->draw, frame);

		vk.CmdEndRendering(cmd);

		Vk_FrameEnd();
	}

	SDL_DestroyWindow(window);
	SDL_Quit();

	return 0;
}

#include "core/core.c"
#include "os/core.c"
#include "vulkan/core.c"
#include "draw/core.c"
#include "game/core.c"
